OWM_API_KEY = 'TU_API_KEY_DE_OPENWEATHERMAP'

TWILIO_ACCOUNT_SID = 'TU_TWILIO_ACCOUNT_SID'
TWILIO_AUTH_TOKEN = 'TU_TWILIO_AUTH_TOKEN'

TWILIO_WHATSAPP_FROM = 'whatsapp:+1xxxxxxxxxxx' 
WHATSAPP_TO = 'whatsapp:+34xxxxxxxxx' 
